import React from 'react'

export const Documentation: React.FC = () => {
  return (
    <div className="w-full max-w-4xl mx-auto py-12 px-6 space-y-20 text-gray-300 leading-relaxed">
      
      {/* 1. Problem Definition (Introduction) happens before Simulation in App.tsx typically, but we can put it here if we want to split it. We'll split it. App.tsx will put Introduction above the visualizer, and the rest below. So this component holds the rest of the documentation. */}
      
      <section id="math" className="space-y-6 scroll-mt-24">
        <div className="flex items-center gap-4">
           <div className="h-px bg-white/10 flex-1"></div>
           <h2 className="text-3xl font-bold text-white tracking-tight">Mathematical Formulation</h2>
           <div className="h-px bg-white/10 flex-1"></div>
        </div>
        
        <p className="text-lg text-gray-400">
          The K-Center problem is an optimization challenge that seeks to minimize the maximum distance any point has to travel to its nearest center. Let <span className="font-mono text-primary-dark">P</span> be the set of nodes and <span className="font-mono text-success">C</span> be the set of selected centers where <span className="font-mono">|C| = k</span>.
        </p>

        <div className="bg-surface/50 p-6 rounded-xl border border-white/5 space-y-4 shadow-inner">
          <p>The distance from a point $p$ to the nearest center is:</p>
          <div className="bg-background px-4 py-3 rounded-lg border border-white/5 font-mono text-primary flex items-center justify-center">
             distance(p, C) = min {`{`} dist(p, c) | c ∈ C {`}`}
          </div>

          <p>The objective function is to minimize the maximum of these distances:</p>
          <div className="bg-background px-4 py-3 rounded-lg border border-white/5 font-mono text-error flex items-center justify-center">
             minimize: max {`{`} distance(p, C) | p ∈ P {`}`}
          </div>
        </div>
      </section>

      <section id="algorithm" className="space-y-6 scroll-mt-24">
        <div className="flex items-center gap-4">
           <div className="h-px bg-white/10 flex-1"></div>
           <h2 className="text-3xl font-bold text-white tracking-tight">The Greedy Algorithm</h2>
           <div className="h-px bg-white/10 flex-1"></div>
        </div>

        <p className="text-lg text-gray-400">
          Because the K-Center problem is NP-Hard, computing the absolute perfect solution scales terribly as the number of nodes increases. We resort to a remarkably simple Greedy Algorithm that guarantees a solution no worse than twice the optimal.
        </p>

        <div className="bg-surface border border-white/10 rounded-xl overflow-hidden shadow-lg">
          <div className="bg-white/5 px-4 py-2 border-b border-white/10">
             <span className="font-mono text-xs text-text-muted">algorithm_k_center.py</span>
          </div>
          <pre className="p-4 overflow-x-auto text-sm font-mono text-gray-300">
            <code className="block">
<span className="text-error">function</span> <span className="text-success">greedyKCenter</span>(P, k):<br/>
{'    '}<span className="text-text-muted">// 1. Pick an arbitrary first point</span><br/>
{'    '}C = {'{'} P[0] {'}'}<br/><br/>
{'    '}<span className="text-error">while</span> |C| {'<'} k:<br/>
{'        '}<span className="text-text-muted">// 2. Find the point farthest from any existing center</span><br/>
{'        '}farthestPoint = <span className="text-primary">null</span><br/>
{'        '}maxDist = -1<br/><br/>
{'        '}<span className="text-error">for</span> p <span className="text-error">in</span> P:<br/>
{'            '}d = <span className="text-success">distanceToNearestCenter</span>(p, C)<br/>
{'            '}<span className="text-error">if</span> d {'>'} maxDist:<br/>
{'                '}maxDist = d<br/>
{'                '}farthestPoint = p<br/><br/>
{'        '}<span className="text-text-muted">// 3. Add it as a center</span><br/>
{'        '}C.add(farthestPoint)<br/><br/>
{'    '}<span className="text-error">return</span> C
            </code>
          </pre>
        </div>
      </section>

      <section id="proof" className="space-y-6 scroll-mt-24">
        <div className="flex items-center gap-4">
           <div className="h-px bg-white/10 flex-1"></div>
           <h2 className="text-3xl font-bold text-white tracking-tight">The 2-Approximation Proof</h2>
           <div className="h-px bg-white/10 flex-1"></div>
        </div>

        <p className="text-lg text-gray-400">
          How do we know this greedy heuristic is good? We can mathematically prove that the radius generated by the Greedy Algorithm (<span className="text-primary font-mono">r</span>) is <strong className="text-white bg-error/20 px-2 py-0.5 rounded">r ≤ 2 * r*</strong> (where <span className="text-success font-mono">r*</span> is the theoretically optimal radius).
        </p>

        <ul className="list-decimal pl-6 space-y-4 bg-surface p-6 rounded-xl border border-white/5">
            <li>Assume the optimal radius is <span className="font-mono text-success">r*</span>.</li>
            <li>When the algorithm selects <span className="font-mono">k</span> centers, suppose it tries to find the <span className="font-mono text-text-muted">k+1</span>th point. Let this point be <span className="font-mono text-white">x</span>, and its distance to the nearest center is <span className="font-mono text-primary">r</span>.</li>
            <li>By the greedy choice, that means <i>every</i> center we selected is at least distance <span className="font-mono text-primary">r</span> apart from each other, and <span className="font-mono text-white">x</span> is also distance <span className="font-mono text-primary">r</span> from all of them.</li>
            <li>We now have <span className="font-mono text-text-muted">k+1</span> points that are all at least <span className="font-mono text-primary">r</span> apart from one another.</li>
            <li>However, the optimal solution only has <span className="font-mono text-white">k</span> centers. By the Pigeonhole Principle, at least two of our <span className="font-mono text-text-muted">k+1</span> points must share the same optimal center cluster.</li>
            <li>The maximum distance between any two points in an optimal cluster is <span className="font-mono text-success">2 * r*</span> (the diameter of the cluster).</li>
            <li>Since these two points are within the same optimal cluster, the distance between them is at most <span className="font-mono text-success">2 * r*</span>. But we established they are at least <span className="font-mono text-primary">r</span> apart.</li>
            <li>Therefore, <span className="font-mono text-primary">r</span> ≤ <span className="font-mono text-success">2 * r*</span>.</li>
        </ul>
      </section>

      <section id="examples" className="space-y-6 scroll-mt-24 mb-20">
        <div className="flex items-center gap-4">
           <div className="h-px bg-white/10 flex-1"></div>
           <h2 className="text-3xl font-bold text-white tracking-tight">Real-World Examples & Uses</h2>
           <div className="h-px bg-white/10 flex-1"></div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="bg-surface border border-white/10 p-5 rounded-xl shadow-lg border-t-4 border-t-primary transition-transform hover:-translate-y-1">
            <h3 className="font-bold text-xl text-white mb-2">Facility Location</h3>
            <p className="text-gray-400">
              Cities must place Fire Stations, Hospitals, or Police Stations such that the maximum response time to any neighborhood is minimized. The farthest house dictates the worst-case scenario.
            </p>
          </div>
          <div className="bg-surface border border-white/10 p-5 rounded-xl shadow-lg border-t-4 border-t-success transition-transform hover:-translate-y-1">
            <h3 className="font-bold text-xl text-white mb-2">Content Delivery Networks (CDN)</h3>
            <p className="text-gray-400">
              Tech giants place cache servers geographically so that no user in the world experiences excessive latency. K-Center ensures the worst-case ping is kept low.
            </p>
          </div>
          <div className="bg-surface border border-white/10 p-5 rounded-xl shadow-lg border-t-4 border-t-error transition-transform hover:-translate-y-1 md:col-span-2">
            <h3 className="font-bold text-xl text-white mb-2">Data Clustering</h3>
            <p className="text-gray-400">
              When training Machine Learning models, establishing a bounded radius for classified clusters ensures anomaly detection isn't skewed by unbounded regional errors.
            </p>
          </div>
        </div>
      </section>

    </div>
  )
}
